### ISSUE TITLE
Request for detailed hyper parameters used

### ISSUE THREAD

**Issue by pavanteja295** [GT-RIPL/Continual-Learning-Benchmark#3]
Hello,
Thanks a lot for your repository. I'm trying to reproduce your results for my experiments and used them as baseline. However I have some trouble in reproducing the exact numbers for MNIST data using MLP network that was reported in the paper. I feel the values for the following missing hyper parameters are missing in the paper and the code
1) L2 regularization coefficient used for L2 baseline.
2) Was lr decay used ? If yes can you shed some details on it .

It would be great if you can share a config file for the best results you got. Although the paper presents some details about these which is very helpful I feel entire configurations are missing.

Thanks in advance

**Comment by yenchanghsu** [comment]
Thanks for your interest in our work. The configurations are defined in the [scripts](https://github.com/GT-RIPL/Continual-Learning-Benchmark/tree/master/scripts) folder. For example, this [line](https://github.com/GT-RIPL/Continual-Learning-Benchmark/blob/master/scripts/split_MNIST_incremental_class.sh#L12) runs the experiment for the L2 baseline. 
To reproduce the paper's results, please run these scripts: [incremental class](https://github.com/GT-RIPL/Continual-Learning-Benchmark/blob/master/scripts/split_MNIST_incremental_class.sh), [incremental domain](https://github.com/GT-RIPL/Continual-Learning-Benchmark/blob/master/scripts/split_MNIST_incremental_domain.sh), and [incremental task](https://github.com/GT-RIPL/Continual-Learning-Benchmark/blob/master/scripts/split_MNIST_incremental_task.sh). The results will be saved to the outputs folder, and the summary will be available at the bottom of each log file. The experiments in the paper were made with PyTorch 1.0.1.

**Comment by pavanteja295** [comment]
Thanks a lot! Very sorry should have checked those scripts.
