### ISSUE TITLE
Grid search script for hyper parameters of EWC, SI, L2

### ISSUE THREAD

**Issue by pavanteja295** [GT-RIPL/Continual-Learning-Benchmark#4]
Hello,

Thanks a lot for uploading the additional scripts for CIFAR-100. I'm trying to replicate the results for various methods through your code. First of all I am very much thankful for the scripts as it helps me avoid the burden of finding the best results through hyper parameter sweep. (Although I would try it in the future.)

One thing I want to ask is how did you perform the search for regularization coefficients for various datasets and architectures? Did you set some intuitive limits for the grid search by looking at the train and test graphs? I'm asking this as I want to replicate this on other datasets lets say CIFAR-10. I can add the scripts for CIFAR-10 and Image net in the future to your repository once I finish experimenting.

Would be great if you share your script for the grid search.

**Comment by yenchanghsu** [comment]
For scanning the regularization coefficient, you can add multiple values after the argument --reg_coef. For example: --reg_coef 0.1 1 10 100. The averaged results of each coefficient will be summarized at the bottom of the log file.

We scan the coefficient in two stages. The first stage has a coarse grid covered a wide range. The second one has a fine grid around the best coarse results.

**Comment by yenchanghsu** [comment]
Please see the above response.
