### ISSUE TITLE
Reproducibility issue

### ISSUE THREAD

**Issue by DigiTurk84** [GT-RIPL/Continual-Learning-Benchmark#5]
Hello,

Thanks for the CIFAR100 scripts. I am having some issues trying to reproduce naive rehearsal results for class incremental learning task. I executed the naive rehearsal 5600 baseline with the following command:

`python -u iBatchLearn.py --dataset CIFAR100 --train_aug --gpuid 0 --repeat 5 --incremental_class --optimizer Adam    --force_out_dim 100 --no_class_remap --first_split_size 20 --other_split_size 20 --schedule 80 120 160 --batch_size 128 --model_name WideResNet_28_2_cifar --model_type resnet --agent_type customization  --agent_name Naive_Rehearsal_5600  --lr 0.001`

Comparing the result with Naive Rehearsal-C reported in https://github.com/GT-RIPL/Continual-Learning-Benchmark/blob/master/fig/results_split_cifar100.png, I obtained the following results:
With pytorch 1.0.0 and torchvision 0.2.2, the final result is around 40%, instead of 51.28.
With pytorch 1.4.0 and torchvision 0.5.0, the final result is around 20%, instead of 51.28.

This is consistently happening with various GPUs (RTX 2080Ti, Titan Xp and Tesla P4/K80).

Could you share the environment configuration you used to obtain reported results on CIFAR100?

**Comment by yenchanghsu** [comment]
Thanks for reporting this issue. There is a commit missing from the last push. Now you should be able to get the reported results. Please use Python 3.6 + PyTorch 1.0.1.post2 or 1.5.1.

The missing commit is for enabling the standard data augmentation for rehearsal. You will see ~10% gain with augmentation.

**Comment by yenchanghsu** [comment]
Please feel free to let me know if any issue.

**Comment by DigiTurk84** [comment]
After running some experiments, I can confirm that after last commit results are consistent with the ones reported.

Thank you.

**Comment by yuxinlyx5** [comment]
Hi, I'm running with Python 3.6 and Pytorch 1.5.1, but I am still getting reproducibility issues. I am getting 45.36 instead of 61.11 for EWC incremental task learning for CIFAR100.
