### ISSUE TITLE
EWC online weights explosion using SGD

### ISSUE THREAD

**Issue by liruiwen** [GT-RIPL/Continual-Learning-Benchmark#6]
The problem is reproducible by running

python -u iBatchLearn.py --dataset CIFAR100 --train_aug --gpuid 0 --repeat 1 --incremental_class --optimizer SGD --force_out_dim 100 --no_class_remap --first_split_size 20 --other_split_size 20 --schedule 1 --batch_size 128 --model_name WideResNet_28_2_cifar --model_type resnet --agent_type customization --agent_name EWC_online --lr 0.001 --reg_coef 100

**Comment by yenchanghsu** [comment]
Different optimizer needs different hyperparameters to work. You will have to tune it. One example is to change your command with "--schedule 5 --lr 0.1 --reg_coef 0.1".
